//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElateService.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string AdditionalInformation
        {
            get
            {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Станьте заказчиком.
        /// </summary>
        public static string BecomeACustomer
        {
            get
            {
                return ResourceManager.GetString("BecomeACustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Станьте исполнителем.
        /// </summary>
        public static string BecomeAnExecutor
        {
            get
            {
                return ResourceManager.GetString("BecomeAnExecutor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to выбрал(а) вас для выполнения заказа.
        /// </summary>
        public static string CandidatureConfirmedNotification
        {
            get
            {
                return ResourceManager.GetString("CandidatureConfirmedNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Категории должны различаться!.
        /// </summary>
        public static string CategoriesErrorMessage
        {
            get
            {
                return ResourceManager.GetString("CategoriesErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Проверьте введенные данные!.
        /// </summary>
        public static string CheckInputData
        {
            get
            {
                return ResourceManager.GetString("CheckInputData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Выбрать исполнителя.
        /// </summary>
        public static string ChooseAsExecutor
        {
            get
            {
                return ResourceManager.GetString("ChooseAsExecutor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Выберите файл.
        /// </summary>
        public static string ChooseFile
        {
            get
            {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Компьютерная помощь.
        /// </summary>
        public static string ComputerHelp
        {
            get
            {
                return ResourceManager.GetString("ComputerHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Код активации аккаунта выслан вам на почту....
        /// </summary>
        public static string ConfirmationCodeToEmail
        {
            get
            {
                return ResourceManager.GetString("ConfirmationCodeToEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string ConfirmNewPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Строительные работы.
        /// </summary>
        public static string ConstructionWorks
        {
            get
            {
                return ResourceManager.GetString("ConstructionWorks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Наши контакты.
        /// </summary>
        public static string Contacts
        {
            get
            {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Договорная.
        /// </summary>
        public static string ContractPrice
        {
            get
            {
                return ResourceManager.GetString("ContractPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы не оценили действия заказчика!.
        /// </summary>
        public static string DontAppreciateCustomersWorkErrorMessage
        {
            get
            {
                return ResourceManager.GetString("DontAppreciateCustomersWorkErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы не оценили работу исполнителя!.
        /// </summary>
        public static string DontAppreciateExecutorsWorkErrorMessage
        {
            get
            {
                return ResourceManager.GetString("DontAppreciateExecutorsWorkErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Загружать фотографии разрешается только в jpeg формате!.
        /// </summary>
        public static string DownloadPhotoErrorMessage
        {
            get
            {
                return ResourceManager.GetString("DownloadPhotoErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Редактировать профиль.
        /// </summary>
        public static string EditProfile
        {
            get
            {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education
        {
            get
            {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Почтовый адрес.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Enter
        {
            get
            {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Введите новый пароль.
        /// </summary>
        public static string EnterNewPassword
        {
            get
            {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Введите адрес вашей почты.
        /// </summary>
        public static string EnterYourEmailAddress
        {
            get
            {
                return ResourceManager.GetString("EnterYourEmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string Executors
        {
            get
            {
                return ResourceManager.GetString("Executors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Файлы к заказу.
        /// </summary>
        public static string FilesToOrder
        {
            get
            {
                return ResourceManager.GetString("FilesToOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Категория исполнителя - 1 .
        /// </summary>
        public static string FirstExecutorCategory
        {
            get
            {
                return ResourceManager.GetString("FirstExecutorCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string ForgetPassword
        {
            get
            {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomePage
        {
            get
            {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Все для дома.
        /// </summary>
        public static string HouseWorks
        {
            get
            {
                return ResourceManager.GetString("HouseWorks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Как это работает?.
        /// </summary>
        public static string HowItWorks
        {
            get
            {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ошибка сервера.
        /// </summary>
        public static string HttpInternalServerError
        {
            get
            {
                return ResourceManager.GetString("HttpInternalServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Искомая страница не найдена.
        /// </summary>
        public static string HttpPageNotFound
        {
            get
            {
                return ResourceManager.GetString("HttpPageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет страницы, удовлетворяющей условиям.
        /// </summary>
        public static string HttpUnprocessableEntity
        {
            get
            {
                return ResourceManager.GetString("HttpUnprocessableEntity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to предлагает вам выполнить заказ.
        /// </summary>
        public static string InviteToCompleteOrderNotification
        {
            get
            {
                return ResourceManager.GetString("InviteToCompleteOrderNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string Lang
        {
            get
            {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оставьте отклик на данный заказ....
        /// </summary>
        public static string LeaveAResponceToThisOrder
        {
            get
            {
                return ResourceManager.GetString("LeaveAResponceToThisOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оставьте отзыв о работе заказчика....
        /// </summary>
        public static string LeaveFeedbackOnTheCustomersWork
        {
            get
            {
                return ResourceManager.GetString("LeaveFeedbackOnTheCustomersWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оставьте отзыв о работе исполнителя....
        /// </summary>
        public static string LeaveFeedbackOnTheExecutorsWork
        {
            get
            {
                return ResourceManager.GetString("LeaveFeedbackOnTheExecutorsWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ElateService - удобный способ найти исполнителя для своего заказа.
        /// </summary>
        public static string MainTitle
        {
            get
            {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оценка: .
        /// </summary>
        public static string Mark
        {
            get
            {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон.
        /// </summary>
        public static string MobilePhone
        {
            get
            {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мои заказы.
        /// </summary>
        public static string MyOrders
        {
            get
            {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мои отклики.
        /// </summary>
        public static string MyRecalls
        {
            get
            {
                return ResourceManager.GetString("MyRecalls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мои ответы.
        /// </summary>
        public static string MyResponces
        {
            get
            {
                return ResourceManager.GetString("MyResponces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет исполнителей, удовлетворяющих условиям!.
        /// </summary>
        public static string NoExecutorsWithSuchProperties
        {
            get
            {
                return ResourceManager.GetString("NoExecutorsWithSuchProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Заказ не найден!.
        /// </summary>
        public static string NoIndentErrorMessage
        {
            get
            {
                return ResourceManager.GetString("NoIndentErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет заказов, удовлетворяющих условиям!.
        /// </summary>
        public static string NoIndentsWithSuchProperties
        {
            get
            {
                return ResourceManager.GetString("NoIndentsWithSuchProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string Notifications
        {
            get
            {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы должны войти в свой аккаунт заказчика, чтобы предложить заказ!.
        /// </summary>
        public static string OfferIndentToExecutorErrorMessage
        {
            get
            {
                return ResourceManager.GetString("OfferIndentToExecutorErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Предложить заказ.
        /// </summary>
        public static string OfferOrder
        {
            get
            {
                return ResourceManager.GetString("OfferOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to на заказ.
        /// </summary>
        public static string OnOrder
        {
            get
            {
                return ResourceManager.GetString("OnOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Упс, что-то пошло не так....
        /// </summary>
        public static string OopsWarningMessage1
        {
            get
            {
                return ResourceManager.GetString("OopsWarningMessage1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Попробуйте повторить ваше действие снова..
        /// </summary>
        public static string OopsWarningMessage2
        {
            get
            {
                return ResourceManager.GetString("OopsWarningMessage2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to или.
        /// </summary>
        public static string Or
        {
            get
            {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Категория заказа.
        /// </summary>
        public static string OrderCategory
        {
            get
            {
                return ResourceManager.GetString("OrderCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Orders
        {
            get
            {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Заказы, которые вы можете предложить.
        /// </summary>
        public static string OrdersWhichICanOffer
        {
            get
            {
                return ResourceManager.GetString("OrdersWhichICanOffer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Patronymic
        {
            get
            {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Фотография.
        /// </summary>
        public static string Photo
        {
            get
            {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1. Разместите заказ.
        /// </summary>
        public static string Point1
        {
            get
            {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Подробно опишите свой заказ. Приложите документы, фотографии и укажите условия — стоимость и сроки..
        /// </summary>
        public static string Point1_1
        {
            get
            {
                return ResourceManager.GetString("Point1.1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2. Изучите отклики.
        /// </summary>
        public static string Point2
        {
            get
            {
                return ResourceManager.GetString("Point2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дождитесь откликов от исполнителей и сравните их. Вся информация под рукой: цена, комментарий и рейтинг исполнителя..
        /// </summary>
        public static string Point2_2
        {
            get
            {
                return ResourceManager.GetString("Point2.2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3. Выберите исполнителя.
        /// </summary>
        public static string Point3
        {
            get
            {
                return ResourceManager.GetString("Point3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Выберите подходящего вам исполнителя и свяжитесь с ним для согласования заказа. После выполнения заказа — оставьте отзыв..
        /// </summary>
        public static string Point3_1
        {
            get
            {
                return ResourceManager.GetString("Point3.1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить отзыв.
        /// </summary>
        public static string PostARecall
        {
            get
            {
                return ResourceManager.GetString("PostARecall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить отклик.
        /// </summary>
        public static string PostAResponce
        {
            get
            {
                return ResourceManager.GetString("PostAResponce", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price
        {
            get
            {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Цена за работу: .
        /// </summary>
        public static string PriceForWork
        {
            get
            {
                return ResourceManager.GetString("PriceForWork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        public static string PrivateOffice
        {
            get
            {
                return ResourceManager.GetString("PrivateOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile
        {
            get
            {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to оставил(а) вам отзыв после работы над заказом.
        /// </summary>
        public static string RecallNotification
        {
            get
            {
                return ResourceManager.GetString("RecallNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отклики.
        /// </summary>
        public static string Recalls
        {
            get
            {
                return ResourceManager.GetString("Recalls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration
        {
            get
            {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Регистрация ElateService.
        /// </summary>
        public static string RegistrationElateService
        {
            get
            {
                return ResourceManager.GetString("RegistrationElateService", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ссылка для восстановления пароля выслана вам на почту....
        /// </summary>
        public static string ResetLinkToEmail
        {
            get
            {
                return ResourceManager.GetString("ResetLinkToEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to предлагает свою кандидатуру для выполнения заказа.
        /// </summary>
        public static string ResponceNotification
        {
            get
            {
                return ResourceManager.GetString("ResponceNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отклики.
        /// </summary>
        public static string Responces
        {
            get
            {
                return ResourceManager.GetString("Responces", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Искать здесь....
        /// </summary>
        public static string SearchHere
        {
            get
            {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Категория исполнителя - 2 .
        /// </summary>
        public static string SecondExecutorCategory
        {
            get
            {
                return ResourceManager.GetString("SecondExecutorCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Send
        {
            get
            {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить заказ.
        /// </summary>
        public static string SendOrder
        {
            get
            {
                return ResourceManager.GetString("SendOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отправить отклик.
        /// </summary>
        public static string SendResponce
        {
            get
            {
                return ResourceManager.GetString("SendResponce", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Контакты заказчика видны только исполнителям его заказов..
        /// </summary>
        public static string ShowPersonalCustomerDataMessage
        {
            get
            {
                return ResourceManager.GetString("ShowPersonalCustomerDataMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Контакты исполнителя видны только его заказчикам. Если вы заинтересованы в услугах этого исполнителя — предложите ему заказ..
        /// </summary>
        public static string ShowPersonalExecutorDataMessage
        {
            get
            {
                return ResourceManager.GetString("ShowPersonalExecutorDataMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сортировать.
        /// </summary>
        public static string Sort
        {
            get
            {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Спорт.
        /// </summary>
        public static string Sport
        {
            get
            {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Были введены некорректные данные, пожалуйста попробуйте снова!.
        /// </summary>
        public static string StandardErrorMessage
        {
            get
            {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname
        {
            get
            {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию!.
        /// </summary>
        public static string ThankyouForRegistration
        {
            get
            {
                return ResourceManager.GetString("ThankyouForRegistration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Просто, выгодно, надежно. Всего 3 шага — и вы найдете.
        /// </summary>
        public static string TitleDescriptionPart1
        {
            get
            {
                return ResourceManager.GetString("TitleDescriptionPart1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  идеального исполнителя для своего заказа..
        /// </summary>
        public static string TitleDescriptionPart2
        {
            get
            {
                return ResourceManager.GetString("TitleDescriptionPart2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Стать заказчиком.
        /// </summary>
        public static string ToBecomeACustomer
        {
            get
            {
                return ResourceManager.GetString("ToBecomeACustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Стать исполнителем.
        /// </summary>
        public static string ToBecomeAnExecutor
        {
            get
            {
                return ResourceManager.GetString("ToBecomeAnExecutor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Туризм.
        /// </summary>
        public static string Tourism
        {
            get
            {
                return ResourceManager.GetString("Tourism", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Перевозки.
        /// </summary>
        public static string TransportationServices
        {
            get
            {
                return ResourceManager.GetString("TransportationServices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string Until
        {
            get
            {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to У вас нету текущих категорий.
        /// </summary>
        public static string YouDontHaveCategories
        {
            get
            {
                return ResourceManager.GetString("YouDontHaveCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ваша оценка заказчику:.
        /// </summary>
        public static string YourEvaluationToTheCustomer
        {
            get
            {
                return ResourceManager.GetString("YourEvaluationToTheCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ваша оценка исполнителю: .
        /// </summary>
        public static string YourEvaluationToThePerformer
        {
            get
            {
                return ResourceManager.GetString("YourEvaluationToThePerformer", resourceCulture);
            }
        }

    }
}
