//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElateService.BLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DAB361B8C8A12E828DE5222355FB5FFD0C976BB0A165195D5060737639A23F5B51D8875333C432FB5B3E70A6F7E7683B240E91010564213279E323B7B845AF7C1492BA637A9BA57F3B9AD8AA534EA1C184B9BBC7C80B06303C83E53011EBC16F6DEAF6CAA702DE764FBEC8B5CE21C615AB0501B22AFD4EE07927F8A043C219697E568B92B67CF5B57607A8DF924D1771CA33CE05E566B7540025D9829AF2CA82519C217E59BDD8EF25BC4F05EEE5A30C40C63DB42C0663860BB7E2DA4099390AF28724AA68A14EF0089576B5668644354A98584F6A0181FFC153098CD862A99FA16B9EDD81515AF0A3347B5032251248A791FEE43CDBD404BE7E45F1D81EBE
")]
        public string GlobalSalt {
            get {
                return ((string)(this["GlobalSalt"]));
            }
        }
    }
}
